### ISSUE TITLE
Not working for alipay.com

### ISSUE THREAD

**Issue by HankAviator** [mmxxooyy/NoQRCodeLogin#3]
script version: 2.0.1
login framework for alipay.com is still QR code by default.

**Comment by mmxxooyy** [comment]
> script version: 2.0.1
> login framework for alipay.com is still QR code by default.

I'm so sorry for seen this issue just now,this script works fine when I visit alipay.com on my Chrome by using Tampermonkey.Can you tell me the button's name you clicked and show me your  browser's console when you visit this website ?

**Comment by HankAviator** [comment]
1. visit https://www.alipay.com
2. button name is "登录", element details for this button:
`<a href="javascript:;" class="am-button button-login" seed="clickMe-amButton" smartracker="on">登录</a>`
3. clicking this button will show qr code login by default.

console output since page load:
```
begin lazy load 17 image files...
index.js:1  AliPay  Copyright © 2004-2019温馨提示：请不要调皮地在此粘贴执行任何内容，这可能会导致您的账户受到攻击，给您带来损失 ！^_^ 为世界带来微小而美好的改变。欢迎加入支付宝： https://job.alibaba.com/zhaopin/position_detail.htm?positionId=41641 
common.js:6 https:
userscript.html?id=741e9e1a-bc7c-464a-806f-6e74c5d5aad1:461 网址匹配,可切换二维码登录： alipay.com
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://seccliprod.alipay.com/api/do.htm?serviceId=webmlog&data=eyJwcm9kdWN0cyI6InNpbmdsZVBhc3N3b3JkIiwiaWQiOiJ3ZWJ8YXV0aGNlbnRlcl9xdWVyeXB3ZF9sb2dpbnw4NjMyY2I5MS00NzQ1LTQxM2YtYmYxYy00NzAyMGJkYjRjYzJSWjExIiwiZWRpdF9zZXJ2ZXJQb2xpY3lfcmVuZGVyIjoiUiIsImVkaXRfc2VydmVyUG9saWN5X3NlbnNvciI6IiIsImVkaXRfc2VydmVyUG9saWN5X3RvbGVyYXRlIjp0cnVlLCJlZGl0X3NlcnZlclBvbGljeV91cGdyYWRlIjpmYWxzZSwiZWRpdF9zZXJ2ZXJQb2xpY3lfZG93bmxvYWRQYXRoIjoiIiwiZWRpdF9icm93c2VyUG9saWN5X3JlbmRlciI6IlIiLCJlZGl0X2Jyb3dzZXJQb2xpY3lfc2Vuc29yIjoiLTEifQ== with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Image (async)
r.report @ index.js:3
(anonymous) @ homeB.htm?redirectType=parent:618
fire @ index.js:4
(anonymous) @ index.js:4
wakeReadyList @ index.js:3
checkReady @ index.js:3
(anonymous) @ index.js:3
o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
fireWith @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
ready @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
B @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
index.js:1 load all, done work.
wWRWqMzCRTZfKBzZsTVy.js:1 [Deprecation] Web MIDI will ask a permission to use even if the sysex is not specified in the MIDIOptions since M77, around September 2019. See https://www.chromestatus.com/feature/5138066234671104 for more details.
Hr @ wWRWqMzCRTZfKBzZsTVy.js:1
n @ wWRWqMzCRTZfKBzZsTVy.js:1
acMain @ wWRWqMzCRTZfKBzZsTVy.js:1
(anonymous) @ wWRWqMzCRTZfKBzZsTVy.js:1
wWRWqMzCRTZfKBzZsTVy.js:1 The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features
ie @ wWRWqMzCRTZfKBzZsTVy.js:1
n @ wWRWqMzCRTZfKBzZsTVy.js:1
rc @ wWRWqMzCRTZfKBzZsTVy.js:1
n @ wWRWqMzCRTZfKBzZsTVy.js:1
Zc @ wWRWqMzCRTZfKBzZsTVy.js:1
n @ wWRWqMzCRTZfKBzZsTVy.js:1
acMain @ wWRWqMzCRTZfKBzZsTVy.js:1
(anonymous) @ wWRWqMzCRTZfKBzZsTVy.js:1
common.js:6 https:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://seccliprod.alipay.com/api/do.htm?serviceId=webmlog&data=eyJlZGl0X2dldENpMSI6LTEsImlkIjoid2VifGF1dGhjZW50ZXJfcXVlcnlwd2RfbG9naW58ODYzMmNiOTEtNDc0NS00MTNmLWJmMWMtNDcwMjBiZGI0Y2MyUloxMSIsImVkaXRfZ2V0Q2kyIjotMSwiZWRpdF9nZXROZXRJbmZvIjotMX0= with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Image (async)
r.report @ index.js:3
(anonymous) @ index.js:3
setTimeout (async)
r.record @ index.js:3
(anonymous) @ login.js:1
(anonymous) @ index.js:4
get @ index.js:4
getCi1 @ index.js:4
system.auth.passwordInit @ login.js:1
(anonymous) @ login.js:1
onReady @ index.js:4
(anonymous) @ login.js:1
o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
add @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
ready @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
init @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
e @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
(anonymous) @ login.js:1
t.exec @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
a @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
(anonymous) @ login.js:1
t.exec @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
e.callback @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
d @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
f @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
load (async)
p @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
c @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.use @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
(anonymous) @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
t.preload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
u.use @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
seajs.use @ homeB.htm?redirectType=parent:246
(anonymous) @ homeB.htm?redirectType=parent:807
```

**Comment by mmxxooyy** [comment]
> 1. visit https://www.alipay.com
> 2. button name is "登录", element details for this button:
>    `<a href="javascript:;" class="am-button button-login" seed="clickMe-amButton" smartracker="on">登录</a>`
> 3. clicking this button will show qr code login by default.
> 
> console output since page load:
> 
> ```
> begin lazy load 17 image files...
> index.js:1  AliPay  Copyright © 2004-2019温馨提示：请不要调皮地在此粘贴执行任何内容，这可能会导致您的账户受到攻击，给您带来损失 ！^_^ 为世界带来微小而美好的改变。欢迎加入支付宝： https://job.alibaba.com/zhaopin/position_detail.htm?positionId=41641 
> common.js:6 https:
> userscript.html?id=741e9e1a-bc7c-464a-806f-6e74c5d5aad1:461 网址匹配,可切换二维码登录： alipay.com
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://seccliprod.alipay.com/api/do.htm?serviceId=webmlog&data=eyJwcm9kdWN0cyI6InNpbmdsZVBhc3N3b3JkIiwiaWQiOiJ3ZWJ8YXV0aGNlbnRlcl9xdWVyeXB3ZF9sb2dpbnw4NjMyY2I5MS00NzQ1LTQxM2YtYmYxYy00NzAyMGJkYjRjYzJSWjExIiwiZWRpdF9zZXJ2ZXJQb2xpY3lfcmVuZGVyIjoiUiIsImVkaXRfc2VydmVyUG9saWN5X3NlbnNvciI6IiIsImVkaXRfc2VydmVyUG9saWN5X3RvbGVyYXRlIjp0cnVlLCJlZGl0X3NlcnZlclBvbGljeV91cGdyYWRlIjpmYWxzZSwiZWRpdF9zZXJ2ZXJQb2xpY3lfZG93bmxvYWRQYXRoIjoiIiwiZWRpdF9icm93c2VyUG9saWN5X3JlbmRlciI6IlIiLCJlZGl0X2Jyb3dzZXJQb2xpY3lfc2Vuc29yIjoiLTEifQ== with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
> Image (async)
> r.report @ index.js:3
> (anonymous) @ homeB.htm?redirectType=parent:618
> fire @ index.js:4
> (anonymous) @ index.js:4
> wakeReadyList @ index.js:3
> checkReady @ index.js:3
> (anonymous) @ index.js:3
> o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> fireWith @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> ready @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> B @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> index.js:1 load all, done work.
> wWRWqMzCRTZfKBzZsTVy.js:1 [Deprecation] Web MIDI will ask a permission to use even if the sysex is not specified in the MIDIOptions since M77, around September 2019. See https://www.chromestatus.com/feature/5138066234671104 for more details.
> Hr @ wWRWqMzCRTZfKBzZsTVy.js:1
> n @ wWRWqMzCRTZfKBzZsTVy.js:1
> acMain @ wWRWqMzCRTZfKBzZsTVy.js:1
> (anonymous) @ wWRWqMzCRTZfKBzZsTVy.js:1
> wWRWqMzCRTZfKBzZsTVy.js:1 The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features
> ie @ wWRWqMzCRTZfKBzZsTVy.js:1
> n @ wWRWqMzCRTZfKBzZsTVy.js:1
> rc @ wWRWqMzCRTZfKBzZsTVy.js:1
> n @ wWRWqMzCRTZfKBzZsTVy.js:1
> Zc @ wWRWqMzCRTZfKBzZsTVy.js:1
> n @ wWRWqMzCRTZfKBzZsTVy.js:1
> acMain @ wWRWqMzCRTZfKBzZsTVy.js:1
> (anonymous) @ wWRWqMzCRTZfKBzZsTVy.js:1
> common.js:6 https:
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://seccliprod.alipay.com/api/do.htm?serviceId=webmlog&data=eyJlZGl0X2dldENpMSI6LTEsImlkIjoid2VifGF1dGhjZW50ZXJfcXVlcnlwd2RfbG9naW58ODYzMmNiOTEtNDc0NS00MTNmLWJmMWMtNDcwMjBiZGI0Y2MyUloxMSIsImVkaXRfZ2V0Q2kyIjotMSwiZWRpdF9nZXROZXRJbmZvIjotMX0= with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
> Image (async)
> r.report @ index.js:3
> (anonymous) @ index.js:3
> setTimeout (async)
> r.record @ index.js:3
> (anonymous) @ login.js:1
> (anonymous) @ index.js:4
> get @ index.js:4
> getCi1 @ index.js:4
> system.auth.passwordInit @ login.js:1
> (anonymous) @ login.js:1
> onReady @ index.js:4
> (anonymous) @ login.js:1
> o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> add @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> ready @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> init @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> e @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:4
> (anonymous) @ login.js:1
> t.exec @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> a @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> (anonymous) @ login.js:1
> t.exec @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> e.callback @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.onload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> d @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> f @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> load (async)
> p @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> o @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> c @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.load @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.use @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> (anonymous) @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> t.preload @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> u.use @ ??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.8/index.js:2
> seajs.use @ homeB.htm?redirectType=parent:246
> (anonymous) @ homeB.htm?redirectType=parent:807
> ```

It seems some error when your page loading,please check this error appears again or not when you turn off 'NoQRcode' script or your Script  Manager.

**Comment by HankAviator** [comment]
error persists

**Comment by mmxxooyy** [comment]
> error persists

That‘s why this script not working.this script run at document load complete,but it appears some errors when you loading this page,so script counld not run.

**Comment by HankAviator** [comment]
the error persists even in incognito mode, i am not sure what caused it even having disabled all extensions.
