### ISSUE TITLE
错位

### ISSUE THREAD

**Issue by ausers** [mmxxooyy/NoQRCodeLogin#4]
![截图](https://user-images.githubusercontent.com/54773815/69825804-7b60a580-124b-11ea-8b70-a15e38684997.png)
当前仅在[百度统计](tongji.baidu.com)发现此问题

**Comment by mmxxooyy** [comment]
问题不大，懒得排查了。。。

**Comment by ausers** [comment]
> 问题不大，懒得排查了。。。

现在排版已经恢复了，我还以为修了。。。

**Comment by ausers** [comment]
那我就关闭issue了

**Comment by mmxxooyy** [comment]
> 那我就关闭issue了

哈哈，拖了半年，百度统计自己修复了。
