### ISSUE TITLE
[Feature request] https://excashier.alipay.com/

### ISSUE THREAD

**Issue by HankAviator** [mmxxooyy/NoQRCodeLogin#7]
Switch to pay on computer instead of QR code by default.

The element name is `switch-tip-btn`

Thank you.

**Comment by mmxxooyy** [comment]
Please tell me how to visit 'https://excashier.alipay.com' correctly

**Comment by HankAviator** [comment]
Go to ctrip.com, choose a hotel that you can cancel for free later, book a room, pay with alipay (but no need to pay), you'll be taken to *Alipay cashier*, where the domain is https://excashier.alipay.com . The landing page will be QR code scan to pay.

**Comment by mmxxooyy** [comment]
> Go to ctrip.com, choose a hotel that you can cancel for free later, book a room, pay with alipay (but no need to pay), you'll be taken to _Alipay cashier_, where the domain is https://excashier.alipay.com . The landing page will be QR code scan to pay.

Done

**Comment by HankAviator** [comment]
I see the codes are updated but it doesn't seem to click to switch to web payment page automatically.

**Comment by mmxxooyy** [comment]
```
if (matchURL('excashier.alipay.com')) {
    var auto = setInterval(function () {
        if ($('#J_tip_qr').css('display') === 'block') {
            setTimeout(function () {
                $('a[seed="J_tip_qr-switchTipBtn"]')[0].click();
            }, 3000);
            clearInterval(auto);
        }
    }, 50);
}
```
Try to increase the timeout number of milliseconds like this at line 554

**Comment by HankAviator** [comment]
It works now somehow even I set it to `50`. Thank you.
